### ISSUE TITLE
New Version ? 

### ISSUE THREAD

**Issue by utkudenis** [SimformSolutionsPvtLtd/flutter_credit_card#168] opened 2024-07-29 10:49 UTC
Hi Developers, 

thank you for offering this amazing package, 

when will you update package with namespace and harmony with  gradle implementation ? 

I want to add it to my updated project but namespace is a problem

**Comment by PRBaraiya** [comment] 2024-08-07 08:59
Duplicate of #162

**Closed by PRBaraiya** 2024-08-07 08:59 UTC
