### ISSUE TITLE
2 cards are visible but 1 is 90° rotated

### ISSUE THREAD

**Issue by Kiritox96** [SimformSolutionsPvtLtd/flutter_credit_card#23] opened 2020-05-29 19:21 UTC
**Describe the bug**

**To Reproduce**
1. Used example on github

**Expected behavior**

2 cards make an X on y-axes

**Comment by YahiaRagae** [comment] 2020-06-10 01:28
@Kiritox96  is it the same one here #14

**Comment by DevarshRanpara** [comment] 2021-01-01 12:59
Duplicate of #14 .

**Closed by DevarshRanpara** 2021-01-01 12:59 UTC
Labels: bug
